"""Phase 1: Initial schemas

Revision ID: 8db3bbe44326
Revises: 
Create Date: 2025-11-27 17:10:16.492355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8db3bbe44326'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("role IN ('admin', 'provider', 'patient')", name='chk_user_role_valid'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('idx_users_email', 'users', ['email'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('idx_users_is_verified', 'users', ['is_verified'], unique=False)
    op.create_index('idx_users_role', 'users', ['role'], unique=False)
    op.create_table('patients',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('blood_type', sa.String(), nullable=True),
    sa.Column('address_line1', sa.String(), nullable=True),
    sa.Column('address_line2', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('postal_code', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('allergies', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('chronic_conditions', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('medications', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('emergency_contact', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('insurance_provider', sa.String(), nullable=True),
    sa.Column('insurance_policy_number', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('date_of_birth <= CURRENT_DATE', name='chk_patient_dob_valid'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('idx_patients_allergies', 'patients', ['allergies'], unique=False, postgresql_using='gin')
    op.create_index('idx_patients_chronic_conditions', 'patients', ['chronic_conditions'], unique=False, postgresql_using='gin')
    op.create_index('idx_patients_dob', 'patients', ['date_of_birth'], unique=False)
    op.create_index('idx_patients_medications', 'patients', ['medications'], unique=False, postgresql_using='gin')
    op.create_index('idx_patients_user_id', 'patients', ['user_id'], unique=False)
    op.create_table('providers',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('specialty', sa.String(), nullable=False),
    sa.Column('license_number', sa.String(), nullable=False),
    sa.Column('credentials', sa.String(), nullable=True),
    sa.Column('languages_spoken', postgresql.JSONB(astext_type=sa.Text()), server_default='["English"]', nullable=False),
    sa.Column('accepted_insurances', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('certifications', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('accepting_new_patients', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('years_of_experience', sa.Integer(), nullable=True),
    sa.Column('additional_info', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('license_number'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('idx_providers_accepted_insurances', 'providers', ['accepted_insurances'], unique=False, postgresql_using='gin')
    op.create_index('idx_providers_accepting_new_patients', 'providers', ['accepting_new_patients'], unique=False)
    op.create_index('idx_providers_languages_spoken', 'providers', ['languages_spoken'], unique=False, postgresql_using='gin')
    op.create_index('idx_providers_specialty', 'providers', ['specialty'], unique=False)
    op.create_index('idx_providers_user_id', 'providers', ['user_id'], unique=False)
    op.create_table('appointments',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('appointment_datetime', sa.DateTime(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), server_default='scheduled', nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('chief_complaint', sa.Text(), nullable=True),
    sa.Column('symptoms', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('diagnosis', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('canceled_by_and_why', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("appointment_datetime >= now() - interval '1 year'", name='chk_appointment_datetime_recent'),
    sa.CheckConstraint("status IN ('scheduled', 'confirmed', 'completed', 'cancelled', 'no_show')", name='chk_appointment_status_valid'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_appointment_diagnosis', 'appointments', ['diagnosis'], unique=False, postgresql_using='gin')
    op.create_index('idx_appointment_no_double_book', 'appointments', ['provider_id', 'appointment_datetime'], unique=True)
    op.create_index('idx_appointment_patient_id', 'appointments', ['patient_id'], unique=False)
    op.create_index('idx_appointment_provider_id', 'appointments', ['provider_id'], unique=False)
    op.create_index('idx_appointment_scheduled_date', 'appointments', ['provider_id', 'appointment_datetime'], unique=False)
    op.create_index('idx_appointment_status', 'appointments', ['status'], unique=False)
    op.create_index('idx_appointment_symptoms', 'appointments', ['symptoms'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_appointment_symptoms', table_name='appointments', postgresql_using='gin')
    op.drop_index('idx_appointment_status', table_name='appointments')
    op.drop_index('idx_appointment_scheduled_date', table_name='appointments')
    op.drop_index('idx_appointment_provider_id', table_name='appointments')
    op.drop_index('idx_appointment_patient_id', table_name='appointments')
    op.drop_index('idx_appointment_no_double_book', table_name='appointments')
    op.drop_index('idx_appointment_diagnosis', table_name='appointments', postgresql_using='gin')
    op.drop_table('appointments')
    op.drop_index('idx_providers_user_id', table_name='providers')
    op.drop_index('idx_providers_specialty', table_name='providers')
    op.drop_index('idx_providers_languages_spoken', table_name='providers', postgresql_using='gin')
    op.drop_index('idx_providers_accepting_new_patients', table_name='providers')
    op.drop_index('idx_providers_accepted_insurances', table_name='providers', postgresql_using='gin')
    op.drop_table('providers')
    op.drop_index('idx_patients_user_id', table_name='patients')
    op.drop_index('idx_patients_medications', table_name='patients', postgresql_using='gin')
    op.drop_index('idx_patients_dob', table_name='patients')
    op.drop_index('idx_patients_chronic_conditions', table_name='patients', postgresql_using='gin')
    op.drop_index('idx_patients_allergies', table_name='patients', postgresql_using='gin')
    op.drop_table('patients')
    op.drop_index('idx_users_role', table_name='users')
    op.drop_index('idx_users_is_verified', table_name='users')
    op.drop_index('idx_users_email', table_name='users', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('users')
    # ### end Alembic commands ###
